version: '3'

services:
    sip:
        build:
            context: ./docker-sip
        network_mode: host
        privileged: true
        ports:
            - "5060:5060/udp"
        env_file: .env
        restart: always
